### ISSUE TITLE
Feature Request: Increased Mining Speed

### ISSUE THREAD

**Issue by K4N0** [goldenapple3/RFDrills#1]
For a Drill and it's cost it would be nice if it drilled Obsidian much faster. It would be nice to have a config option for drill speeds. Or possibly have it Drill in a 3x3 but at the cost of 9x more power. I use Capacitors to recharge the tools i use and they hold up to 50mil RF.

**Comment by gardenappl** [comment]
The tools are already configurable. You'll probably have to wait for 3x3 mining because I'm not planning on making upgrades/mining modes soon.

**Comment by goldenapple3** [comment]
Dammit >_<  Sorry, I'm still to this issue tracker.

**Comment by gardenappl** [comment]
Actually, the 1x3x1 mode is a thing, so... Closing!

**Comment by K4N0** [comment]
I thought you wanted to make it different than redstone arsenal not just change the appearance of their tools.
