### ISSUE TITLE
Incompatibility with veinminer

### ISSUE THREAD

**Issue by Staegrin** [goldenapple3/RFDrills#13]
RFDrills is currently incompatible with veinminer. Instead of using RF the tool gets damaged instantly and disappears like with a vanilla tool that gets broken. 

Otherwise great mod and keep up the good work.

**Comment by gardenappl** [comment]
Here, grab this update and see how that works http://minecraft.curseforge.com/mc-mods/229846-rfdrills/files/2238365

Also, sorry for slight delay on the update and thanks for the support :+1:

**Comment by Staegrin** [comment]
Tools from new version works perfectly with veinminer.
