### ISSUE TITLE
Crusher area of effect

### ISSUE THREAD

**Issue by Staegrin** [goldenapple3/RFDrills#15]
Not sure if intended but the area of effect 3x3x3 and 5x5x5 are only possible if you can pass through walls. or first dig a 1x1 tunnel to the middle block of the cubes.

When working with these large areas of effect they are centred on the middle block. 

So when digging into a wall with the setting 5x5x5 you will actually only create a hole of 5x5x3, with 3 being the depth. 
![2015-05-16_18 07 18](https://cloud.githubusercontent.com/assets/8494635/7666889/7ac39396-fbf6-11e4-9596-0065009c20aa.png) The oak log represents the block that was mined.
Digging into a wall with the setting 3x3x3 you will actually only create a hole of 3x3x2, with 2 being the depth.
![2015-05-16_18 07 25](https://cloud.githubusercontent.com/assets/8494635/7666893/8add4d4e-fbf6-11e4-8aad-fb7241cd0b24.png)

So the only way to mine a cube of the size as set by the mode of the tool, would be to first dig a 1x1x2 hole for the 5x5x5 mode or a 1x1x1 hole for the 3x3x3 mode.

**Comment by gardenappl** [comment]
This is intended. I can change it if it's annoying, but for now that's how it is.

**Comment by Staegrin** [comment]
Fine by me. Just wanted to make sure it was intentional. This is the same method used by the bound pickaxe from bloodmagic as opposed to the method used in botania for the terra shatterer.
