### ISSUE TITLE
class cast exception

### ISSUE THREAD

**Issue by Razaekel** [goldenapple3/RFDrills#16]
When trying to auto-fill the recipe for a chainsaw in AE2, the server crashes with the following:

java.lang.ClassCastException: goldenapple.rfdrills.item.ItemChainsaw cannot be cast to goldenapple.rfdrills.item.ItemDrill
    at goldenapple.rfdrills.crafting.ShapedUpgradeRecipe.func_77572_b(ShapedUpgradeRecipe.java:22) ~[ShapedUpgradeRecipe.class:?]

log: http://paste.ee/p/lnIlt

**Comment by gardenappl** [comment]
Are you using the newest version? I'm almost exactly sure I fixed this already. Go grab the the newest version and see if that helps: http://minecraft.curseforge.com/mc-mods/229846-rfdrills/files

**Comment by gardenappl** [comment]
I can probably close this now?
