### ISSUE TITLE
crusher skips blocks

### ISSUE THREAD

**Issue by rrongol** [goldenapple3/RFDrills#18]
The flux crusher skips harvesting all blocks with the same x, y, or z coordinate as the target block.  (Same issue in ItemSoulCrusher.java).  The if statement in ItemFluxCrusher.java is causing this. 

ItemFluxCrusher.java
if (!(a == x || b == y || c == z))

Change the or to and, and it should work fine.

if (!(a == x && b == y && c == z))

**Comment by gardenappl** [comment]
Wow. That's a major derp.
Thank you for pointing this out, I'll release a fix tomorrow.
