### ISSUE TITLE
Enchants

### ISSUE THREAD

**Issue by piedpipr314** [goldenapple3/RFDrills#19]
The Advanced Electric Drill, while saying that is enchantable, is only so in creative mode with an anvil and book.  It does work with an enchanting table and a random enchant in survival.  I was just hoping to be able to pick which enchant I wanted.  Can this be fixed?
Edit: I'm using a sword-only enchant, I'm a derp.  Still not sure why this wouldn't work, but I can accept it.

**Comment by gardenappl** [comment]
Wait, does that mean that tool-only enchants don't work with anvils either? If that's the case, I'll look into it tomorrow.
