### ISSUE TITLE
Cobalt, Ardite disapears

### ISSUE THREAD

**Issue by SuperSandro2000** [goldenapple3/RFDrills#20]
You can't mine Cobalt and Ardite with the Flux Infused Crusher because it disappears after you minned it.

**Comment by gardenappl** [comment]
Are you mining it in 1x1 mode or does that happen only with the AoE effect?

Also, are you using Iguana Tweaks? I've heard that it messes with tools from other mods.

**Comment by gardenappl** [comment]
I will look into improving the harvesting algorithm, but some more information would still be useful.

**Comment by SuperSandro2000** [comment]
I use 5x5 and Iguana Tweaks. Sometimes it is working when I mine the ore directly and do not use the aoe.

**Comment by gardenappl** [comment]
The update containg the bugfix should be public now: http://minecraft.curseforge.com/mc-mods/229846-rfdrills/files/2257240
