### ISSUE TITLE
Dark Soularium Crusher not craftable (details below)

### ISSUE THREAD

**Issue by ArukaAlter** [goldenapple3/RFDrills#22]
![](http://i.imgur.com/6OONgif.png)
When the EnderIO integration on Simply Jetpacks is disabled, the Dark Soularium Crusher can not be obtained, as the component item isn't registered.

**Comment by gardenappl** [comment]
Huh. That's something that I didn't consider at all.

Fortunately, that's easy to fix. My mod already adds "replacement items" if Simply Jetpacks isn't installed. I'll just change the "if Simply Jetpacks is installed" algorithm to "is Dark Soularium registrered" and everything should work.

**Comment by gardenappl** [comment]
I just realised that SimplyJetpacks uses 1 item for all of it's components. So the item is always registered, but there is no recipes and textures for Dark Soularium if EIO is disabled.

It looks like I'll have to use reflection to check the SimplyJetpacks config.

**Comment by gardenappl** [comment]
Just released version 1.6.3 here: http://minecraft.curseforge.com/mc-mods/229846-rfdrills/files/2257240

Please tell me that it fixes things.
