### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by TheOnlyRupert** [goldenapple3/RFDrills#23]
Newest version (1.7) crashes server side

http://pastebin.com/4b68fM9G

**Comment by BBoldt** [comment]
ditto
https://gist.github.com/BBoldt/ccef733f0e57babbe434

**Comment by therealericbj** [comment]
...me too...

http://pastebin.com/XzR1Vk0v

Happy Hunting.

**Comment by gardenappl** [comment]
Huh. Okay.
I will try to fix this today. If you need a soultion immediately, set the config option for "Mining Animation Type" to 0 and restart the server.

**Comment by gardenappl** [comment]
This should fix things. http://minecraft.curseforge.com/mc-mods/229846-rfdrills/files/2258941
