### ISSUE TITLE
NoClassDefFoundError crash if WAILA is no present

### ISSUE THREAD

**Issue by artubi** [goldenapple3/RFDrills#24]
Hi
Minecraft will crash during loading screen if WAILA is not present.

Tested with:
RFDrills-1.7.10-1.7.1

Log:
http://pastebin.com/tnyh20XD

Adding WAILA fixes this issue.

**Comment by gardenappl** [comment]
Oh.
That's quite a derp. I'll fix it today though.

**Comment by artubi** [comment]
Tested the latest version RFDrills-1.7.10-1.7.2. No longer crashes if WAILA is not present.

**Comment by gardenappl** [comment]
Sorry for not responding earlier. I released a fix to Curseforge yesterday but forgot to push it to Github.
