### ISSUE TITLE
 What are the Required Libraries?

### ISSUE THREAD

**Issue by nmarshall23** [goldenapple3/RFDrills#25]
I have just CoFH Core and Thermal Foundation installed, and RFDrills does not have a creative tab. 

I can see that RFDrills is loaded on the Main menu's Mods list.

Does RFDrills require ThermalExpansion?

**Comment by gardenappl** [comment]
Either Thermal Expansion or EnderIO.

**Comment by nmarshall23** [comment]
You should make that clearer on the curseforge page. I was very confused.

**Comment by gardenappl** [comment]
I thought that
"This little addon to Thermal Expansion and EnderIO adds drills and chainsaws"
should be enough. But I'll edit the page to make it a bit more clear, don't worry.
