### ISSUE TITLE
Feature Request: Harvesting Drill

### ISSUE THREAD

**Issue by K4N0** [goldenapple3/RFDrills#4]
A drill or upgrade to use it like a sickle for farming a 5x5 at a time and when right clicked it tills dirt like a hoe.

**Comment by gardenappl** [comment]
I'm surprised I still haven't thought of this. That's a good suggestion!

**Comment by gardenappl** [comment]
1.6 added the Flux Hoe which also harvests blocks like a 3x3 sickle. Close enough? I'll probably close this.
