### ISSUE TITLE
Feature Request: MultiTool

### ISSUE THREAD

**Issue by K4N0** [goldenapple3/RFDrills#5]
Diamond Saw blade upgrade: makes the Drill be able to Chop down wood fast.
Diamond Excavator upgrade: makes the drill be able to harvest a big area, 3x3 4x4 of wheat, grass, for farming and upon right click makes it till soil like a hoe.
Diamond Blade upgrade: Make it so that it causes 14 attack damage to mobs.
Shift right click while holding the drill to change modes.

**Comment by gardenappl** [comment]
Multitools won't be a thing (except for the Final Tier tool). Chainsaws are already planned, as well as plant harvesters. Not sure about weapons.

**Comment by gardenappl** [comment]
The Flux-Infused Crusher is now available in the 1.3 update, so I'll probably close this...

**Comment by Shayleel** [comment]
I think you should do a Crusher version for EnderIo too, for those who don't want to play with Thermal Expansion.

**Comment by gardenappl** [comment]
I will, but it will take a while because I have some big plans for that.

I want the Dark Steel Crusher to be a cheaper, less powerful version of the Flux-Infused Crusher, but with upgrades. So you'll have to earn your 3x3, 5x5 or (maybe?) 7x7 modes.

**Comment by gardenappl** [comment]
http://minecraft.curseforge.com/mc-mods/229846-rfdrills/files
The EnderIO crusher is done, so I'll probably close this.
